# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneylog',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
