# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_money'),
        ('billing', '0002_moneylog_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneylog',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='task.Task'),
        ),
    ]
