# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_moneylog_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneylog',
            name='task',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.Task'),
        ),
    ]
