# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20160522_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
